### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by samwel-mongare** [Tumworobere/Recipe-App#17]
### The following are details of our Recipe-App project and responsibilities:
Project link: https://github.com/Tumworobere/Recipe-App/projects/1

- The project has a team of three ( @AnselemOdims, @Tumworobere, and @Mosams 
  Team A: @AnselemOdims 
  Team B: @Tumworobere 
  Team C: @Mosams

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
